export const DefaultStyle = {
  FONT_SIZE: {
    HUGE: "4rem",
    BIGGER: "3rem",
    BIG: "2rem",
    MEDIUM: "1.5rem",
    SMALL_MEDIUM: "1.2rem",
    SMALLER: "1.1rem",
    SMALL: "1rem",
    VERY_SMALL: "0.9rem",
    TINY: "0.8rem",
  },
  MEDIA_SIZE: {
    MOBILE_S: "320px",
    MOBILE_M: "375px",
    MOBILE_L: "425px",
    TABLET: "768px",
    LAPTOP: "1024px",
    LAPTOP_M: "1280px",
    LAPTOP_L: "1440px",
    DESKTOP: "2560px",
  },
  MAX_DEVICE: {
    MOBILE_S: `(max-width: 320px)`,
    MOBILE_M: `(max-width: 375px)`,
    MOBILE_L: `(max-width: 425px)`,
    TABLET: `(max-width: 768px)`,
    LAPTOP: `(max-width: 1024px)`,
    LAPTOP_M: `(max-width: 1280px)`,
    LAPTOP_L: `(max-width: 1440px)`,
    DESKTOP: `(max-width: 2560px)`,
  },
  MIN_DEVICE: {
    MOBILE_S: `(min-width: 320px)`,
    MOBILE_M: `(min-width: 375px)`,
    MOBILE_L: `(min-width: 425px)`,
    TABLET: `(min-width: 768px)`,
    LAPTOP: `(min-width: 1024px)`,
    LAPTOP_M: `(min-width: 1280px)`,
    LAPTOP_L: `(min-width: 1440px)`,
    DESKTOP: `(min-width: 2560px)`,
  },
  COLOR: {
    PRIMARY: "#cc9808",
    SECONDARY: "#fad77d",
    DARK_SECONDARY: "#d1a01f",
    TERTIARY: "#fff5d9",
    DARK: "#1c191f",
    GRAY: "#666666",
    DARK_GRAY: "#4f4f4f",
    MEDIUM_GRAY: "#c9c9c9",
    LIGHT_GRAY: "#f4f4f4",
    VERY_LIGHT_GRAY: "#fafafa",
    LIGHT: "#fffaeb",
    SUCCESS: "#aed169",
    DARK_SUCCESS: "#7ba132",
    ERROR: "#d16969",
    DARK_ERROR: "#a13232",
    DISABLED: "#f0f0f0",
    DARK_DISABLED: "#d9d9d9",
  },
};
